apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-microapp
  labels:
    app: microapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microapp
  template:
    metadata:
      labels:
        app: microapp
    spec:
      containers:
      - name: container-microapp
        image: srikanta1219/micro1:$BUILD.NUMBER
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: micro1-svc
  labels:
    app: micro1
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  nodePort: 30001
  selector:
    app: micro1
    
