apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-shanviapp
  labels:
    app: shanviapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shanviapp
  template:
    metadata:
      labels:
        app: shanviapp
    spec:
      containers:
      - name: container-shanviapp
        image: srikanta1219/shanvi:11
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shanviapp-svc
  labels:
    app: shanviapp
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: shanviapp
    
